### ISSUE TITLE
Razer Kiyo Pro HDR not working

### ISSUE THREAD

**Issue by callistix** [soyersoyer/cameractrls#42] opened 2024-03-15 13:58 UTC
Hi, just got my new Razer Kiyo Pro and cameractrls seems to support most features well, except H264 and HDR.

The controls show up:

```
./cameractrls.py -d /dev/video0 -l | grep -i hdr
 kiyo_pro_hdr = None    ( values: off, on )
 kiyo_pro_hdr_mode = None       ( values: bright, dark )
```

but they are always staying at "None", no matter what I set them to.
Changing them seems to have no effect at all, neither visually nor from the controls:

```
$ ./cameractrls.py -d /dev/video0 -c pixelformat=MJPG
$ ./cameractrls.py -d /dev/video0 -c fps=30
$ ./cameractrls.py -d /dev/video0 -c kiyo_pro_hdr=on
$ ./cameractrls.py -d /dev/video0 -c kiyo_pro_hdr_mode=bright
$ ./cameractrls.py -d /dev/video0 -l | egrep -i "pixelformat|hdr|fps"
 kiyo_pro_hdr = None    ( values: off, on )
 kiyo_pro_hdr_mode = None       ( values: bright, dark )
 pixelformat = MJPG     ( values: YUYV, MJPG, H264, NV12 )
 fps = 30       ( values: 60, 30, 24, 20, 15, 10, 5 )
```

It doesn't seem to matter which pixelformat I choose either.

**Comment by soyersoyer** [comment] 2024-03-18 11:03
The effect of  HDR is only visible in direct sunlight.
The Kiyo Pro firmware does not have a getter function for some of its controls, so they are always 'None'. But you can set them.
This seems duplicate of #4.

**Closed** 2024-03-21 16:01 UTC
